# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PFE\app\interfaces\menuprincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authentification(object):
    def setupUi(self, Authentification):
        Authentification.setObjectName("Authentification")
        Authentification.setEnabled(True)
        Authentification.resize(600, 400)
        self.bg = QtWidgets.QWidget(Authentification)
        self.bg.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.bg.setStyleSheet("QWidget#bg{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.bg.setObjectName("bg")
        self.widget = QtWidgets.QWidget(self.bg)
        self.widget.setGeometry(QtCore.QRect(0, 90, 601, 191))
        self.widget.setStyleSheet("QLineEdit{\n"
"    border-width: 1px; \n"
"    border-style: solid; \n"
"    qproperty-alignment: \'AlignVCenter | AlignCenter\';\n"
"    padding:10px;\n"
" }")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 601, 169))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 12pt \"HP Simplified\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.username_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username_field.setEnabled(True)
        self.username_field.setStyleSheet("")
        self.username_field.setObjectName("username_field")
        self.verticalLayout.addWidget(self.username_field, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("font: 12pt \"HP Simplified\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.password_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_field.setStyleSheet("QLineEdit#username_field{\n"
"    border-width: 1px; \n"
"    border-style: solid; \n"
"    border-color: transparent transparent rgb(255, 152, 152) transparent;\n"
"    qproperty-alignment: \'AlignVCenter | AlignCenter\';\n"
" }")
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.verticalLayout.addWidget(self.password_field, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.bg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 64))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.bg)
        self.line.setGeometry(QtCore.QRect(240, 70, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.connect_button = QtWidgets.QPushButton(self.bg)
        self.connect_button.setGeometry(QtCore.QRect(236, 340, 128, 20))
        self.connect_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 5px;\n"
"padding: 2px 5px;")
        self.connect_button.setIconSize(QtCore.QSize(16, 16))
        self.connect_button.setObjectName("connect_button")
        self.error_label = QtWidgets.QLabel(self.bg)
        self.error_label.setGeometry(QtCore.QRect(190, 290, 221, 20))
        self.error_label.setStyleSheet("font: 10pt \"HP Simplified\";\n"
"color: rgb(255, 0, 0);")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(Authentification)
        QtCore.QMetaObject.connectSlotsByName(Authentification)

    def retranslateUi(self, Authentification):
        _translate = QtCore.QCoreApplication.translate
        Authentification.setWindowTitle(_translate("Authentification", "Authentifier"))
        self.label.setText(_translate("Authentification", "Nom d\'utilisateur"))
        self.username_field.setPlaceholderText(_translate("Authentification", "Nom d\'utilisateur"))
        self.label_3.setText(_translate("Authentification", "Mot de passe"))
        self.password_field.setPlaceholderText(_translate("Authentification", "Mot de passe"))
        self.connect_button.setText(_translate("Authentification", "Connecter"))
